services:
  garage:
    image: dxflrs/garage:v2.3.0
    container_name: garage
    command: /garage server
    volumes:
      - ./garage/garage.toml:/etc/garage.toml:ro
      - garage-data:/var/lib/garage
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"

volumes:
  garage-data:
