{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-ceph" (include "objectlens.fullname" .)) .Values.secret.name }}
  labels:
    {{- include "objectlens.labels" . | nindent 4 }}
type: Opaque
stringData:
  CEPH_S3_ENDPOINT_URL: {{ .Values.secret.cephS3EndpointUrl | quote }}
  CEPH_S3_REGION: {{ .Values.secret.cephS3Region | quote }}
  CEPH_S3_ACCESS_KEY_ID: {{ .Values.secret.cephS3AccessKeyId | quote }}
  CEPH_S3_SECRET_ACCESS_KEY: {{ .Values.secret.cephS3SecretAccessKey | quote }}
  CEPH_S3_DEFAULT_BUCKET: {{ .Values.secret.cephS3DefaultBucket | quote }}
  CEPH_S3_VERIFY_SSL: {{ .Values.secret.cephS3VerifySsl | quote }}
{{- end }}
