apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: objectlens
spec:
  selector:
    app: objectlens
    component: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
